"""
LangGraph shared state definition for the AFDAD pipeline.

This is the single source of truth for data flowing between graph nodes.
Every node reads from and writes to this TypedDict.
"""

from __future__ import annotations

from typing import Any, TypedDict


class AFDADState(TypedDict, total=False):
    """Shared graph state for the AFDAD pipeline.

    Every field is optional (``total=False``) so that individual nodes
    can return partial updates without specifying every key.
    """

    # ── Input ──
    task: str
    """The coding problem description."""

    task_id: str
    """Unique identifier for the task."""

    test_cases: list[dict[str, Any]]
    """Official test cases for the task."""

    entry_point: str
    """Function entry point name for the task."""

    # ── Planning ──
    plan: str
    """Algorithmic plan generated by the planner."""

    # ── Student Generation ──
    student_code: str
    """Code generated by the student SLM."""

    # ── Execution ──
    execution_result: dict[str, Any]
    """Execution result from the sandbox (serialised ExecutionResult)."""

    # ── Failure Analysis ──
    failure_description: str
    """Structured failure description."""

    failure_embedding: list[float]
    """Embedding vector of the failure description."""

    failure_cluster: str
    """Assigned failure cluster name."""

    # ── Repair ──
    repaired_code: str
    """Code produced by the expert repair team."""

    repair_trace: dict[str, Any]
    """Full repair trajectory (serialised RepairTrajectory)."""

    repair_verified: bool
    """Whether the critic verified the repair."""

    # ── Pipeline Control ──
    success: bool
    """Whether the task was solved successfully."""

    expert_called: bool
    """Whether the expert model was invoked."""

    trajectory_id: str
    """Unique trajectory identifier for this run."""

    attempt: int
    """Current repair attempt number."""

    max_attempts: int
    """Maximum repair attempts allowed."""

    # ── Distillation ──
    training_example: dict[str, Any]
    """Generated training example (serialised TrainingExample)."""
